### ISSUE TITLE
Problems loading resources in Confluence

### ISSUE THREAD

**Issue by Macroz** [NitorCreations/nitor-backend#8]
Loading these pages often fails. The result is a page with a collection of broken styles and/or images. Especially happens using wifi and less so using wired connection at the office.

https://inside.nitor.zone/display/nitor/KAMU-konsepti
https://inside.nitor.zone/display/nitor/Yhteystiedot

Tested in Chrome/Linux and Chrome/OSX.

**Comment by gmokki** [comment]
I think has been fixed last summer/fall. I haven't noticed any problems since then.
